/**
 * GeoNexus - Centralized Spatial Dataset
 * Region: Visakhapatnam, Andhra Pradesh, India (IND-AP-VIZ)
 */

const GEONEXUS_DATA = {
  region: {
    country: "IND",
    countryName: "India",
    state: "AP",
    stateName: "Andhra Pradesh",
    district: "VIZ",
    districtName: "Visakhapatnam",
    crs: "EPSG:4326 (WGS 84)",
    baseCoordinates: { lat: 17.6868, lng: 83.2185, elevation: 24.5 },
    dataStatus: "Spatial Dataset"
  },
  metrics: {
    totalLandParcels: 1248,
    total3DBuildings: 186,
    registeredPropertyUnits: 4832,
    availableFlats: 327,
    undergroundAssets: 614,
    spatialConflicts: 18,
    lidarCoverage: 72,
    threeGSCoverage: 34,
    verifiedProperties: 3940,
    activePermits: 42
  },
  buildings: [
    {
      id: "BLD01",
      name: "Marina Residency",
      type: "Residential",
      parcelId: "P-42-1A",
      surveyNo: "42/1A",
      floorsCount: 6,
      unitsCount: 24,
      builtYear: 2021,
      heightMeters: 21.0,
      footprintSqMt: 850,
      coordinates: { lat: 17.6912, lng: 83.2210 },
      threePos: { x: -35, z: -25 },
      address: "Beach Road, Pandurangapuram, Visakhapatnam",
      status: "Verified",
      dataStatus: "Building Cadastre Data",
      floors: [
        { floorNum: 0, label: "Ground Floor", units: ["G01", "G02", "G03", "G04"] },
        { floorNum: 1, label: "Floor 1", units: ["U101", "U102", "U103", "U104"] },
        { floorNum: 2, label: "Floor 2", units: ["U201", "U202", "U203", "U204"] },
        { floorNum: 3, label: "Floor 3", units: ["U301", "U302", "U303", "U304"] },
        { floorNum: 4, label: "Floor 4", units: ["U401", "U402", "U403", "U404"] },
        { floorNum: 5, label: "Floor 5", units: ["U501", "U502", "U503", "U504"] }
      ]
    },
    {
      id: "BLD02",
      name: "Marina Twin Tower A",
      type: "Residential",
      parcelId: "P-42-1B",
      surveyNo: "42/1B",
      floorsCount: 10,
      unitsCount: 40,
      builtYear: 2022,
      heightMeters: 34.0,
      footprintSqMt: 1200,
      coordinates: { lat: 17.6935, lng: 83.2245 },
      threePos: { x: 35, z: -40 },
      address: "Maharanipeta, Visakhapatnam",
      status: "Verified",
      dataStatus: "Building Cadastre Data",
      floors: [
        { floorNum: 0, label: "Ground Floor", units: ["G01", "G02", "G03", "G04"] },
        { floorNum: 1, label: "Floor 1", units: ["U101", "U102", "U103", "U104"] },
        { floorNum: 2, label: "Floor 2", units: ["U201", "U202", "U203", "U204"] },
        { floorNum: 3, label: "Floor 3", units: ["U301", "U302", "U303", "U304"] },
        { floorNum: 4, label: "Floor 4", units: ["U401", "U402", "U403", "U404"] }
      ]
    },
    {
      id: "BLD03",
      name: "Sagar Vista",
      type: "Residential",
      parcelId: "P-88-3",
      surveyNo: "88/3",
      floorsCount: 8,
      unitsCount: 32,
      builtYear: 2020,
      heightMeters: 26.5,
      footprintSqMt: 980,
      coordinates: { lat: 17.6890, lng: 83.2150 },
      threePos: { x: -45, z: 30 },
      address: "Siripuram Junction, Visakhapatnam",
      status: "Verified",
      dataStatus: "Building Cadastre Data",
      floors: [
        { floorNum: 0, label: "Ground Floor", units: ["G01", "G02", "G03", "G04"] },
        { floorNum: 1, label: "Floor 1", units: ["U101", "U102", "U103", "U104"] },
        { floorNum: 2, label: "Floor 2", units: ["U201", "U202", "U203", "U204"] },
        { floorNum: 3, label: "Floor 3", units: ["U301", "U302", "U303", "U304"] }
      ]
    },
    {
      id: "BLD04",
      name: "Tech Park Alpha",
      type: "Commercial",
      parcelId: "P-104-A",
      surveyNo: "104/A",
      floorsCount: 7,
      unitsCount: 14,
      builtYear: 2023,
      heightMeters: 29.0,
      footprintSqMt: 1600,
      coordinates: { lat: 17.6980, lng: 83.2310 },
      threePos: { x: 48, z: 35 },
      address: "Rushikonda IT SEZ, Visakhapatnam",
      status: "Verified",
      dataStatus: "Building Cadastre Data",
      floors: [
        { floorNum: 0, label: "Ground Floor", units: ["G01", "G02"] },
        { floorNum: 1, label: "Floor 1", units: ["U101", "U102"] },
        { floorNum: 2, label: "Floor 2", units: ["U201", "U202"] },
        { floorNum: 3, label: "Floor 3", units: ["U301", "U302"] }
      ]
    },
    {
      id: "BLD05",
      name: "Geo Heights",
      type: "Residential",
      parcelId: "P-55-2C",
      surveyNo: "55/2C",
      floorsCount: 5,
      unitsCount: 20,
      builtYear: 2023,
      heightMeters: 18.5,
      footprintSqMt: 750,
      coordinates: { lat: 17.6868, lng: 83.2185 },
      threePos: { x: 0, z: 0 },
      address: "Sector 4, MVP Colony, Visakhapatnam, AP 530017",
      status: "Verified",
      isFlagship: true,
      dataStatus: "Flagship Digital Twin",
      floors: [
        { floorNum: 0, label: "Ground Floor", units: ["G01", "G02", "G03", "G04"] },
        { floorNum: 1, label: "Floor 1", units: ["U101", "U102", "U103", "U104"] },
        { floorNum: 2, label: "Floor 2", units: ["U201", "U202", "U203", "U204"] },
        { floorNum: 3, label: "Floor 3", units: ["U301", "U302", "U303", "U304"] },
        { floorNum: 4, label: "Floor 4", units: ["U401", "U402", "U403", "U404"] }
      ]
    }
  ],

  properties: [
    {
      ulpin: "IND-AP-VIZ-BLD05-F03-U302",
      unitNumber: "Flat 302",
      unitCode: "U302",
      buildingId: "BLD05",
      buildingName: "Geo Heights",
      floorNumber: 3,
      floorLabel: "3rd Floor",
      propertyType: "Residential Apartment",
      configuration: "3 BHK",
      areaSqFt: 1250,
      carpetAreaSqFt: 1040,
      bathrooms: 2,
      balconies: 1,
      parking: "Available (Dedicated Slot B-14)",
      facing: "North-East",
      status: "AVAILABLE FOR SALE",
      statusCode: "available_sale",
      price: "₹72,00,000",
      priceRaw: 7200000,
      maintenancePerMonth: "₹2,500",
      furnishing: "Semi-Furnished",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "11.1m Above Ground Level",
      absoluteElevation: "35.6m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "98.4%",
      isFlagship: true,
      owner: {
        name: "Rajesh Kumar",
        phoneMasked: "+91 XXXXX XXXXX",
        emailMasked: "owner@example.com",
        preferredContact: "Email",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information - Cadastral Record"
      },
      coordinates: { lat: 17.686824, lng: 83.218541, z: 11.1 },
      features: [
        "Vastu Compliant Layout",
        "Piped Natural Gas (PNG) Provision",
        "Subsurface Fiber Connection",
        "Rainwater Harvesting Connected",
        "EV Charging Capable Parking"
      ]
    },
    {
      ulpin: "IND-AP-VIZ-BLD05-F03-U301",
      unitNumber: "Flat 301",
      unitCode: "U301",
      buildingId: "BLD05",
      buildingName: "Geo Heights",
      floorNumber: 3,
      floorLabel: "3rd Floor",
      propertyType: "Residential Apartment",
      configuration: "2 BHK",
      areaSqFt: 980,
      carpetAreaSqFt: 810,
      bathrooms: 2,
      balconies: 1,
      parking: "Available (Slot B-13)",
      facing: "East",
      status: "AVAILABLE FOR RENT",
      statusCode: "available_rent",
      price: "₹24,000/mo",
      priceRaw: 24000,
      maintenancePerMonth: "₹2,000",
      furnishing: "Unfurnished",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "11.1m Above Ground Level",
      absoluteElevation: "35.6m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "97.8%",
      owner: {
        name: "Suresh Varma",
        phoneMasked: "+91 XXXXX XXXXX",
        emailMasked: "owner2@example.com",
        preferredContact: "Phone",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information"
      },
      coordinates: { lat: 17.686800, lng: 83.218500, z: 11.1 }
    },
    {
      ulpin: "IND-AP-VIZ-BLD05-F02-U202",
      unitNumber: "Flat 202",
      unitCode: "U202",
      buildingId: "BLD05",
      buildingName: "Geo Heights",
      floorNumber: 2,
      floorLabel: "2nd Floor",
      propertyType: "Residential Apartment",
      configuration: "3 BHK",
      areaSqFt: 1250,
      carpetAreaSqFt: 1040,
      bathrooms: 2,
      balconies: 1,
      parking: "Slot B-08",
      facing: "North-East",
      status: "OCCUPIED",
      statusCode: "occupied",
      price: "₹70,00,000",
      priceRaw: 7000000,
      maintenancePerMonth: "₹2,500",
      furnishing: "Fully Furnished",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "7.4m Above Ground Level",
      absoluteElevation: "31.9m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "98.1%",
      owner: {
        name: "Private Resident",
        phoneMasked: "Private",
        emailMasked: "Private",
        preferredContact: "N/A",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information"
      },
      coordinates: { lat: 17.686824, lng: 83.218541, z: 7.4 }
    },
    {
      ulpin: "IND-AP-VIZ-BLD01-F04-U402",
      unitNumber: "Flat 402",
      unitCode: "U402",
      buildingId: "BLD01",
      buildingName: "Marina Residency",
      floorNumber: 4,
      floorLabel: "4th Floor",
      propertyType: "Luxury Sea View Flat",
      configuration: "3 BHK",
      areaSqFt: 1450,
      carpetAreaSqFt: 1220,
      bathrooms: 3,
      balconies: 2,
      parking: "Covered Slot M-04",
      facing: "East (Sea Facing)",
      status: "AVAILABLE FOR SALE",
      statusCode: "available_sale",
      price: "₹95,00,000",
      priceRaw: 9500000,
      maintenancePerMonth: "₹3,200",
      furnishing: "Fully Furnished",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "14.8m Above Ground Level",
      absoluteElevation: "39.3m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "99.1%",
      owner: {
        name: "P. Venkat Rao",
        phoneMasked: "+91 XXXXX XXXXX",
        emailMasked: "marina_owner@example.com",
        preferredContact: "Phone",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information"
      },
      coordinates: { lat: 17.691250, lng: 83.221050, z: 14.8 }
    },
    {
      ulpin: "IND-AP-VIZ-BLD02-F06-U601",
      unitNumber: "Tower A Flat 601",
      unitCode: "U601",
      buildingId: "BLD02",
      buildingName: "Marina Twin Tower A",
      floorNumber: 6,
      floorLabel: "6th Floor",
      propertyType: "High-Rise Apartment",
      configuration: "4 BHK",
      areaSqFt: 2100,
      carpetAreaSqFt: 1780,
      bathrooms: 4,
      balconies: 3,
      parking: "2 Covered Slots T-12, T-13",
      facing: "North",
      status: "AVAILABLE FOR SALE",
      statusCode: "available_sale",
      price: "₹1,45,00,000",
      priceRaw: 14500000,
      maintenancePerMonth: "₹4,500",
      furnishing: "Unfurnished",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "22.2m Above Ground Level",
      absoluteElevation: "46.7m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "98.9%",
      owner: {
        name: "K. Anuradha",
        phoneMasked: "+91 XXXXX XXXXX",
        emailMasked: "tower_owner@example.com",
        preferredContact: "Email",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information"
      },
      coordinates: { lat: 17.693520, lng: 83.224510, z: 22.2 }
    },
    {
      ulpin: "IND-AP-VIZ-BLD03-F02-U204",
      unitNumber: "Flat 204",
      unitCode: "U204",
      buildingId: "BLD03",
      buildingName: "Sagar Vista",
      floorNumber: 2,
      floorLabel: "2nd Floor",
      propertyType: "Residential Apartment",
      configuration: "2 BHK",
      areaSqFt: 1050,
      carpetAreaSqFt: 890,
      bathrooms: 2,
      balconies: 1,
      parking: "Slot S-09",
      facing: "South",
      status: "AVAILABLE FOR RENT",
      statusCode: "available_rent",
      price: "₹21,000/mo",
      priceRaw: 21000,
      maintenancePerMonth: "₹1,800",
      furnishing: "Semi-Furnished",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "7.4m Above Ground Level",
      absoluteElevation: "31.9m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "97.2%",
      owner: {
        name: "M. Nageswara Rao",
        phoneMasked: "+91 XXXXX XXXXX",
        emailMasked: "sagar_owner@example.com",
        preferredContact: "Phone",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information"
      },
      coordinates: { lat: 17.689010, lng: 83.215020, z: 7.4 }
    },
    {
      ulpin: "IND-AP-VIZ-BLD04-F03-U301",
      unitNumber: "Suite 301",
      unitCode: "U301",
      buildingId: "BLD04",
      buildingName: "Tech Park Alpha",
      floorNumber: 3,
      floorLabel: "3rd Floor",
      propertyType: "IT Office Workspace",
      configuration: "Commercial Office",
      areaSqFt: 3400,
      carpetAreaSqFt: 2950,
      bathrooms: 2,
      balconies: 0,
      parking: "4 Dedicated Slots TP-01..04",
      facing: "North-West",
      status: "AVAILABLE FOR RENT",
      statusCode: "available_rent",
      price: "₹1,35,000/mo",
      priceRaw: 135000,
      maintenancePerMonth: "₹12,000",
      furnishing: "Warm Shell Workspace",
      spatialStatus: "3D Boundary Verified",
      relativeElevation: "12.0m Above Ground Level",
      absoluteElevation: "36.5m AMSL",
      realityCaptureStatus: "3DGS Asset Ready",
      lidarConfidence: "99.4%",
      owner: {
        name: "AP SEZ Authority",
        phoneMasked: "+91 XXXXX XXXXX",
        emailMasked: "sez_admin@example.com",
        preferredContact: "Email",
        ownershipVerified: "Government ID Verified",
        disclaimer: "Contact Information"
      },
      coordinates: { lat: 17.698040, lng: 83.231060, z: 12.0 }
    }
  ],

  parcels: [
    {
      id: "P-55-2C",
      surveyNo: "55/2C",
      ulpin: "IND-AP-VIZ-P55-2C",
      areaSqMt: 1850,
      areaAcres: 0.457,
      landUse: "Residential High Density (R-3)",
      buildingCount: 1,
      associatedBuilding: "BLD05 (Geo Heights)",
      propertyCount: 20,
      zone: "MVP Urban Sector",
      coordinates: { lat: 17.6868, lng: 83.2185 },
      boundaryPoints: [[-20, -18], [20, -18], [22, 18], [-18, 20]],
      spatialStatus: "2D Cadastre Matched to 3D Twin",
      dataStatus: "Cadastral Parcel"
    },
    {
      id: "P-42-1A",
      surveyNo: "42/1A",
      ulpin: "IND-AP-VIZ-P42-1A",
      areaSqMt: 2100,
      areaAcres: 0.518,
      landUse: "Residential Mixed (R-2)",
      buildingCount: 1,
      associatedBuilding: "BLD01 (Marina Residency)",
      propertyCount: 24,
      zone: "Beach Road Coastal Strip",
      coordinates: { lat: 17.6912, lng: 83.2210 },
      boundaryPoints: [[-55, -45], [-15, -45], [-15, -5], [-55, -5]],
      spatialStatus: "2D Cadastre Matched to 3D Twin",
      dataStatus: "Cadastral Parcel"
    },
    {
      id: "P-42-1B",
      surveyNo: "42/1B",
      ulpin: "IND-AP-VIZ-P42-1B",
      areaSqMt: 2800,
      areaAcres: 0.691,
      landUse: "High Rise Residential (R-4)",
      buildingCount: 1,
      associatedBuilding: "BLD02 (Marina Twin Tower A)",
      propertyCount: 40,
      zone: "Maharanipeta Civic Zone",
      coordinates: { lat: 17.6935, lng: 83.2245 },
      boundaryPoints: [[10, -60], [55, -60], [55, -20], [10, -20]],
      spatialStatus: "2D Cadastre Matched to 3D Twin",
      dataStatus: "Cadastral Parcel"
    },
    {
      id: "P-88-3",
      surveyNo: "88/3",
      ulpin: "IND-AP-VIZ-P88-3",
      areaSqMt: 2400,
      areaAcres: 0.593,
      landUse: "Residential Multi-Family",
      buildingCount: 1,
      associatedBuilding: "BLD03 (Sagar Vista)",
      propertyCount: 32,
      zone: "Siripuram Commercial-Residential",
      coordinates: { lat: 17.6890, lng: 83.2150 },
      boundaryPoints: [[-65, 10], [-25, 10], [-25, 50], [-65, 50]],
      spatialStatus: "2D Cadastre Matched to 3D Twin",
      dataStatus: "Cadastral Parcel"
    },
    {
      id: "P-104-A",
      surveyNo: "104/A",
      ulpin: "IND-AP-VIZ-P104-A",
      areaSqMt: 4200,
      areaAcres: 1.037,
      landUse: "Commercial IT / Tech Park",
      buildingCount: 1,
      associatedBuilding: "BLD04 (Tech Park Alpha)",
      propertyCount: 14,
      zone: "Rushikonda Special Economic Zone",
      coordinates: { lat: 17.6980, lng: 83.2310 },
      boundaryPoints: [[25, 15], [70, 15], [70, 60], [25, 60]],
      spatialStatus: "2D Cadastre Matched to 3D Twin",
      dataStatus: "Cadastral Parcel"
    }
  ],
  infrastructure: [
    {
      id: "UTIL-W203",
      name: "Water Pipeline W-203",
      type: "water",
      typeName: "Potable Water Main",
      depth: -3.8,
      diameterMm: 450,
      material: "Ductile Iron (DI)",
      pressureBar: 4.5,
      color: "#0284c7",
      path: [
        { x: -60, y: -3.8, z: 10 },
        { x: -10, y: -3.8, z: 3 },
        { x: 5, y: -3.8, z: -2 },
        { x: 60, y: -3.8, z: -10 }
      ],
      hasConflict: true,
      conflictId: "CONF-1024",
      status: "Active - Monitoring Spatial Clearance",
      dataStatus: "Subsurface Utility"
    },
    {
      id: "UTIL-S101",
      name: "Sewer Line S-101",
      type: "sewer",
      typeName: "Trunk Sewer Gravity Line",
      depth: -7.5,
      diameterMm: 600,
      material: "Reinforced Concrete Pipe (RCP)",
      color: "#a16207",
      path: [
        { x: -50, y: -7.5, z: -40 },
        { x: -15, y: -7.5, z: -15 },
        { x: 20, y: -7.5, z: 15 },
        { x: 50, y: -7.5, z: 40 }
      ],
      hasConflict: false,
      status: "Active - Normal",
      dataStatus: "Subsurface Utility"
    },
    {
      id: "UTIL-P405",
      name: "Power Conduit P-405",
      type: "power",
      typeName: "33kV Underground Feeder Cable",
      depth: -2.2,
      diameterMm: 200,
      material: "XLPE Armoured in Duct Bank",
      color: "#eab308",
      path: [
        { x: -40, y: -2.2, z: 50 },
        { x: -5, y: -2.2, z: 20 },
        { x: 25, y: -2.2, z: -20 },
        { x: 40, y: -2.2, z: -50 }
      ],
      hasConflict: false,
      status: "Active - High Voltage",
      dataStatus: "Subsurface Utility"
    },
    {
      id: "UTIL-G88",
      name: "Gas Main G-88",
      type: "gas",
      typeName: "Piped Natural Gas (PNG) City Feeder",
      depth: -1.8,
      diameterMm: 150,
      material: "Carbon Steel Epoxy Coated",
      color: "#ef4444",
      path: [
        { x: -55, y: -1.8, z: -20 },
        { x: -30, y: -1.8, z: -22 },
        { x: 10, y: -1.8, z: 12 },
        { x: 55, y: -1.8, z: 20 }
      ],
      hasConflict: true,
      conflictId: "CONF-1025",
      status: "Active - Caution Zone",
      dataStatus: "Subsurface Utility"
    },
    {
      id: "UTIL-MTR-BL",
      name: "Metro Blue Line Tunnel",
      type: "metro",
      typeName: "Underground Transit Corridor (Twin Tube)",
      depth: -18.5,
      diameterMm: 5800,
      material: "Segmental Precast Concrete Lining",
      color: "#8b5cf6",
      path: [
        { x: -70, y: -18.5, z: 0 },
        { x: -20, y: -18.5, z: 0 },
        { x: 20, y: -18.5, z: 0 },
        { x: 70, y: -18.5, z: 0 }
      ],
      hasConflict: true,
      conflictId: "CONF-1026",
      status: "Active - Transit Easement Buffer",
      dataStatus: "Subsurface Utility"
    }
  ],

  conflicts: [
    {
      id: "CONF-1024",
      code: "CONFLICT #1024",
      title: "Building Foundation vs Water Pipeline W-203",
      type: "Subsurface Utility / Foundation Proximity",
      severity: "HIGH",
      severityColor: "#ef4444",
      distanceMeters: 1.8,
      mandatedBufferMeters: 3.0,
      affectedAssets: ["Geo Heights (BLD05 Foundation)", "Water Pipeline W-203"],
      location3D: { x: 3.2, y: -3.8, z: -1.5 },
      status: "Needs Review",
      description: "Water Pipeline W-203 runs within 1.8m horizontal clearance of Geo Heights deep basement pile cap foundation (minimum required clearance: 3.0m). Vibration and excavation risk during foundation maintenance.",
      recommendedAction: "Mandate structural protective encasement or execute 1.2m lateral diversion of pipeline segment W-203-S4.",
      reportedDate: "2026-08-14",
      dataStatus: "Spatial Conflict"
    },
    {
      id: "CONF-1025",
      code: "CONFLICT #1025",
      title: "Gas Main G-88 Crossing Storm Culvert",
      type: "Utility-on-Utility Crossing",
      severity: "MEDIUM",
      severityColor: "#f59e0b",
      distanceMeters: 0.4,
      mandatedBufferMeters: 0.8,
      affectedAssets: ["Gas Main G-88", "Storm Drain SD-44"],
      location3D: { x: -30.5, y: -1.8, z: -22.0 },
      status: "In Progress",
      description: "Piped natural gas pipeline passes directly over masonry storm water drainage line with insufficient 400mm vertical buffer.",
      recommendedAction: "Add insulating protective sleeve and warning tile marker.",
      reportedDate: "2026-08-22",
      dataStatus: "Spatial Conflict"
    },
    {
      id: "CONF-1026",
      code: "CONFLICT #1026",
      title: "Metro Blue Line Easement Buffer Zone",
      type: "Subway Corridor Heavy Loading Limit",
      severity: "LOW",
      severityColor: "#3b82f6",
      distanceMeters: 6.2,
      mandatedBufferMeters: 5.0,
      affectedAssets: ["Metro Blue Line Tunnel", "Tech Park Alpha (BLD04 Ground Piles)"],
      location3D: { x: 35.0, y: -18.5, z: 12.0 },
      status: "Approved with Monitoring",
      description: "Commercial tower pile depth falls within the secondary structural envelope of Metro Blue Line. Clearance is 6.2m (meets 5m threshold with live vibration sensors).",
      recommendedAction: "Maintain continuous real-time seismic & vibration sensor telemetry.",
      reportedDate: "2026-07-05",
      dataStatus: "Spatial Conflict"
    }
  ],

  lidarMetadata: {
    datasetName: "Visakhapatnam LiDAR - MVP Urban Sector",
    captureDate: "2026-02-18",
    sensorType: "Airborne LiDAR Riegl VUX-1UAV",
    crs: "EPSG:4326 / EPSG:32644 (UTM 44N)",
    pointCount: "2,450,000",
    pointCountRaw: 2450000,
    pointDensity: "12.4 pts/m²",
    verticalAccuracy: "±3.2 cm",
    horizontalAccuracy: "±5.0 cm",
    elevationRange: "0.0m - 118.4m AMSL",
    areaCovered: "8.2 km²",
    classificationClasses: [
      { id: 2, name: "Ground", color: "#854d0e" },
      { id: 5, name: "High Vegetation", color: "#16a34a" },
      { id: 6, name: "Building Roofs & Facades", color: "#2563eb" },
      { id: 9, name: "Water Bodies", color: "#06b6d4" },
      { id: 17, name: "Underground Assets / Subsurface Voids", color: "#8b5cf6" }
    ],
    status: "LiDAR Point Cloud Matrix"
  },

  realityCaptureMetadata: {
    assetName: "Geo Heights - Photogrammetry & 3DGS Scene",
    captureMethod: "Drone Photogrammetry + Handheld LiDAR Photogrammetry",
    gaussianSplatCount: "1,850,000 Gaussians",
    spatialResolution: "4mm GSD",
    processingPipeline: "3DGS Nerfstudio / GIS Georeferencing",
    status: "3DGS Reality View Scene",
    disclaimer: "3DGS Asset Photogrammetry Scene"
  },

  spatialEvents: [
    {
      id: "EV-901",
      timestamp: "2 mins ago",
      type: "building_verified",
      title: "Building BLD05 Verified",
      desc: "3D digital twin geometry for Geo Heights validated against municipal cadastral survey 55/2C.",
      badge: "CADASTRE",
      badgeColor: "success"
    },
    {
      id: "EV-902",
      timestamp: "18 mins ago",
      type: "conflict_detected",
      title: "Conflict #1024 Detected",
      desc: "Underground clearance between Water Pipeline W-203 and Geo Heights foundation flagged at 1.8m.",
      badge: "SPATIAL ALERT",
      badgeColor: "danger"
    },
    {
      id: "EV-903",
      timestamp: "45 mins ago",
      type: "lidar_loaded",
      title: "LiDAR Dataset Loaded",
      desc: "Visakhapatnam 2.45M point-cloud layer indexed with EPSG:4326 projection.",
      badge: "LiDAR",
      badgeColor: "info"
    },
    {
      id: "EV-904",
      timestamp: "1 hour ago",
      type: "property_updated",
      title: "Property U302 Updated",
      desc: "Unit U302 (Flat 302) marked AVAILABLE FOR SALE with 3D ULPIN IND-AP-VIZ-BLD05-F03-U302.",
      badge: "PROPERTY",
      badgeColor: "primary"
    },
    {
      id: "EV-905",
      timestamp: "3 hours ago",
      type: "utility_mapped",
      title: "Subsurface Utility Mapped",
      desc: "Metro Blue Line 5.8m tunnel corridor geometry mapped at depth level -18.5m.",
      badge: "UNDERGROUND",
      badgeColor: "purple"
    }
  ],

  glossary: {
    "ULPIN": "Unique Land Parcel Identification Number (Bhu-Aadhar) – Extended in GeoNexus into a 3D Unit-Level Spatial Identifier for vertical properties (Building → Floor → Flat).",
    "LiDAR": "Light Detection and Ranging – Remote sensing technology using pulsed laser beams to produce millimeter-accurate 3D point-cloud spatial coordinates.",
    "DEM": "Digital Elevation Model – Bare-earth raster topographic representation without buildings or trees.",
    "DSM": "Digital Surface Model – Topographic surface capturing the tops of buildings, trees, and other surface features.",
    "3D Tiles": "OGC Open standard streaming format for massive 3D geospatial content (buildings, point clouds, terrain meshes).",
    "Gaussian Splatting": "3DGS – Novel rasterization technique using 3D Gaussians for photorealistic real-time scene rendering from photographic captures.",
    "PostGIS": "Spatial database extender for PostgreSQL that enables GIS spatial geometry queries (ST_Intersects, ST_3DDistance, ST_Volume).",
    "Spatial Conflict": "Automatic geometric clash detection between underground utility easements (pipes/cables) and building foundations.",
    "Digital Twin": "A live, computable 3D virtual replica of physical land, building floors, units, and subterranean assets."
  }
};
